application: fresh-argon-152122
runtime: go
api_version: go1
version: 5

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  script: _go_app

automatic_scaling:
  max_concurrent_requests: 80
  min_pending_latency: 1000ms
  max_idle_instances: 1